POST http://localhost:8080/
Content-Type: text/plain

https://example.com
###
POST http://localhost:8080/api/shorten
Content-Type: application/json
Accept-Encoding: gzip

{
  "url": "https://ok.ru"
}
###
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "login": "test_user",
  "password": "test_password",
  "email": "test_email"
}
###
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "login": "test_user",
  "password": "test_password"
}